/* =====================================================================
   사랑이야기스튜디오 — 기본 정보 설정 파일
   ---------------------------------------------------------------------
   ★ 전화번호, 주소, 영업시간, 가격, 갤러리 사진은 모두 이 파일에서 고치면
     홈페이지 전체에 자동으로 반영됩니다.
   ★ 따옴표("") 안의 글자만 바꿔주세요. 쉼표(,)와 괄호는 지우지 마세요.
   ※ 아래 정보는 네이버 플레이스(2026년 9월 기준)를 참고해 넣었습니다.
   ===================================================================== */

window.STUDIO = {
  name: "사랑이야기스튜디오",
  nameEn: "LOVESTORY STUDIO",
  slogan: "1996년부터, 구미 가족의 가장 행복한 순간을 기록합니다",

  phone: "054-455-8859",                       // 대표 전화번호
  mobile: "",                                  // 문자 받을 휴대폰 번호 (넣으면 휴대폰에서 '문자로 문의'가 동작합니다)
  address: "경북 구미시 금오산로14길 2 (원평동 427-1)",
  addressDetail: "금오산 사거리에서 금오산 방향 100m 우측 건물 · 금오초등학교 맞은편 · 다담뜰 뷔페 5m 전",
  parking: "무료 주차 10대 가능 (건물 뒤 전용주차장, 건물 앞·옆). 도착 전 문의해 주세요.",
  transit: "대경선 구미역에서 가까워요",
  mapSearch: "사랑이야기스튜디오 구미",
  mapLat: "36.1249955",                         // 지도 위치 (위도)
  mapLng: "128.3334216",                        // 지도 위치 (경도)
  naverPlace: "https://map.naver.com/p/entry/place/12029069",
  naverReviews: "https://m.place.naver.com/place/12029069/review/visitor",   // 네이버 방문자 리뷰 목록

  hours: [
    ["월 · 목 · 금 · 토", "09:00 – 18:00"],
    ["일요일", "09:00 – 17:00"],
    ["점심시간", "12:00 – 13:00"],
    ["화 · 수요일", "정기휴무"],
  ],
  hoursNote: "모든 촬영은 예약 후 방문하시면 기다림 없이 촬영하실 수 있어요. 화·수요일은 정기휴무입니다.",

  // 링크가 없으면 "" 로 비워두세요. 비어 있으면 버튼이 자동으로 숨겨집니다.
  naverBooking: "https://m.booking.naver.com/booking/6/bizes/145890",   // 네이버 예약
  naverTalk: "https://talk.naver.com/wcbz2s",                           // 네이버 톡톡 상담
  kakao: "",          // 카카오톡 채널 채팅 주소가 생기면 넣어주세요
  instagram: "https://www.instagram.com/gumi_studio_lovestory",
  cafe: "https://cafe.naver.com/gumils",
  blog: "",

  owner: "정태영",
  bizInfo: "대표 정태영 · 경북 구미시 금오산로14길 2",

  // 가격표 위에 표시되는 안내 문구 (필요 없으면 "" 로 비워주세요)
  priceNotice: "네이버 플레이스 이벤트 가격 기준입니다. 이벤트 가격은 바뀔 수 있으니 예약 시 한 번 더 확인해 주세요.",

  // 네이버 방문자 리뷰 (숫자가 바뀌면 여기서 고쳐주세요)
  review: {
    score: "4.94",
    count: "344",
    asOf: "2026년 9월 기준",
    keywords: [["친절해요", 245], ["자연스럽게 연출해줘요", 205], ["시설이 깔끔해요", 165], ["분위기가 편안해요", 133], ["보정을 꼼꼼하게 해줘요", 98], ["가격이 합리적이에요", 74]],
  },
};

/* ---------------------------------------------------------------------
   촬영 분야 (메뉴와 첫 화면 카드에 쓰입니다)
   --------------------------------------------------------------------- */
window.CATEGORIES = [
  { key: "family",   name: "가족사진",     en: "Family",   page: "family.html",   img: "images/family-big.jpg",          desc: "우리 네 식구부터 3대 대가족, 칠순·팔순 기념까지" },
  { key: "remind",   name: "리마인드웨딩", en: "Remind Wedding", page: "remind.html", img: "images/remind-couple.jpg", desc: "결혼기념일, 회갑·칠순, 다시 입는 웨딩드레스" },
  { key: "friends",  name: "우정사진",     en: "Friendship", page: "friends.html", img: "images/friends-ribbon.jpg",     desc: "오랜 친구, 동창, 모임과 함께 남기는 추억" },
  { key: "id",       name: "증명사진",     en: "ID Photo", page: "id-photo.html", img: "images/id-1.jpg",               desc: "취업·이력서·자격증, 인상이 좋아 보이는 증명사진" },
  { key: "passport", name: "여권사진",     en: "Passport", page: "passport.html", img: "images/passport-1.jpg",         desc: "외교부 규격에 맞춘 정확한 여권사진" },
  { key: "profile",  name: "프로필사진",   en: "Profile",  page: "profile.html",  img: "images/profile-1.jpg",          desc: "SNS·명함·오디션용 프로필, 부모님 장수사진" },
];

/* ---------------------------------------------------------------------
   가격표
   - price: 화면에 크게 표시되는 가격
   - was: 원래 가격 (있으면 줄 그어서 함께 표시, 없으면 "" 또는 지우기)
   - best: true 로 두면 '추천' 표시가 붙습니다.
   --------------------------------------------------------------------- */
window.PRICES = {
  family: [
    { name: "소가족 사진", people: "2 ~ 4인", was: "300,000원", price: "100,000원", items: ["28×36cm 고급 몰딩 액자 1개", "포켓사진 (촬영 인원수만큼)", "미니 탁상액자 1개", "웹용 액자 작업본 파일 제공", "캐주얼 흰셔츠 무료 제공"] },
    { name: "대가족 사진", people: "5인 이상", was: "610,000원", price: "380,000원", best: true, items: ["28×36cm 고급 몰딩 액자 1개", "부모님 메이크업 & 헤어 풀케어", "부모님 드레스 & 턱시도 제공", "지갑용 사진 (인원수만큼) · 미니 탁상액자 1개", "웹용 액자 작업본 파일 제공", "캐주얼 흰셔츠 무료 대여", "5인 기준 · 1인 추가 5만원 (반려견도 1인)"] },
    { name: "칠순 · 팔순 상차림", people: "부부 2인 기준", was: "560,000원", price: "280,000원", items: ["28×36cm 고급 몰딩 액자 1개", "부부 메이크업 & 헤어 풀케어", "부부 한복 포함", "포켓사진 2매 · 미니 탁상액자 1개", "웹용 액자 작업본 파일 제공"] },
  ],
  remind: [
    { name: "리마인드웨딩", people: "부부 2인", was: "560,000원", price: "280,000원", best: true, items: ["28×36cm 고급 몰딩 액자 1개", "부부 메이크업 & 헤어 풀케어", "부부 드레스 & 턱시도 포함", "포켓사진 2매 · 미니 탁상액자 1개", "웹용 액자 작업본 파일 제공"] },
    { name: "웨딩촬영", people: "2인", was: "910,000원", price: "680,000원", items: ["28×36cm 아크릴 베젤 액자 1개", "12×17cm 사진 3장 출력", "부부 메이크업 & 헤어 풀케어", "부부 드레스 & 턱시도 포함", "포켓사진 2매 · 미니 탁상액자 1개", "웹용 액자 작업본 파일 제공"] },
  ],
  friends: [
    { name: "우정사진", people: "2 ~ 4인", price: "1인 50,000원", items: ["12×17cm 1장 + 5×7cm 1장 (동일 사진)", "의상 1벌 직접 준비 (흰셔츠 무료 대여)", "드레스·파티복·한복·경성복·교복 대여 1벌 3만원", "메이크업 & 헤어 추가 시 할인", "웹용 액자 작업본 파일 제공"] },
    { name: "우정사진", people: "5인 이상", price: "1인 30,000원", best: true, items: ["12×17cm 1장 + 5×7cm 1장 (동일 사진)", "의상 1벌 직접 준비 (흰셔츠 무료 대여)", "드레스·파티복·한복·경성복·교복 대여 1벌 3만원", "메이크업 & 헤어 추가 시 할인", "웹용 액자 작업본 파일 제공"] },
  ],
  id: [
    { name: "증명 · 여권사진", people: "1인", price: "30,000원", best: true, items: ["용도에 맞는 규격으로 촬영", "세부 구성은 전화로 안내해 드려요"] },
  ],
  passport: [
    { name: "증명 · 여권사진", people: "1인", price: "30,000원", best: true, items: ["외교부 여권 규격 3.5×4.5cm", "세부 구성은 전화로 안내해 드려요"] },
  ],
  profile: [
    { name: "프로필사진 기본촬영", people: "1인", price: "100,000원", best: true, items: ["용도와 분위기에 맞춘 촬영", "세부 구성은 상담 시 안내해 드려요"] },
  ],
};

/* ---------------------------------------------------------------------
   고객 후기 (홈페이지에 카드로 보여집니다)
   - ★ 네이버에 남겨주신 후기를 옮길 때는 꼭 손님께 "홈페이지에 올려도 될까요?"
     동의를 받은 뒤 넣어주세요. (후기 글의 권리는 작성하신 손님께 있어요)
   - name 은 "김**" 처럼 가려서 적어주세요.
   - type 은 가족사진 / 리마인드웨딩 / 우정사진 / 증명사진 / 여권사진 / 프로필사진 중 하나
     (가족사진 페이지에는 type 이 "가족사진"인 후기만 보여요)
   - 후기가 하나도 없으면 후기 칸은 자동으로 숨겨집니다.
   - 아래 예시 줄의 맨 앞 // 를 지우고 내용을 바꾸면 됩니다.
   --------------------------------------------------------------------- */
//   - 사진·영상은 images/reviews 폴더에 넣고 media 에 적어주세요.
//     사진: { src: "images/reviews/사진이름.jpg" }   영상: { video: "images/reviews/영상이름.mp4", poster: "images/reviews/표지.jpg" }
window.REVIEWS = [
  // { name: "김**", type: "가족사진", date: "2026.09", text: "손님이 남겨주신 후기 내용을 여기에 적어주세요.", media: [{ src: "images/reviews/sample.jpg" }] },
  {"id":"6ab77e3e287a30675e973d94","name":"승**","type":"가족사진","date":"2026.09","text":"엄마의 버킷리스트라\n언니가 알아보고 결정했어요~^^\n명절인데도 이쁜사진 잘 찍어주셔서 감사해요\n사춘기아들도 잘 구슬려 멋진사진 찍어주신 사장님 최고입니다\n사진도 너무 다 맘에들어요\n한복도 다양하고 종류도 많고\n다 어울리는 한복으로 초이스해주셔서\n더 멋진 사진이 나올수있었던거 같아요\n수정본도 넘 기대됩니다♡","media":[]},
  {"id":"6ab4cae09df1b1c97df95b7c","name":"m**","type":"가족사진","date":"2026.09","text":"친절하게 너무 잘해요. 머리 스타일도 꼼꼼하게 봐주십니다.👍👍👍👍👍","media":[{"src":"images/reviews/6ab4cae09df1b1c97df95b7c-1.jpg"}]},
  {"id":"6ab4da4b758f3e223e9689c6","name":"숭**","type":"가족사진","date":"2026.09","text":"메이크업 해주시는 분도 너무 친절하시고 요즘 스타일로 화장해주세요\n촬영 작가님은 자연스러운 포즈를 유추해주실려고 노력 많이 해주시고 웃음 짓게 해주셨어요 너무 감사합니다^^","media":[{"src":"images/reviews/6ab4da4b758f3e223e9689c6-1.jpg"}]},
  {"id":"6ab9ea0a122c555ed4c4b43f","name":"l**","type":"가족사진","date":"2026.09","text":"촬영내내 편안한 분위기로  \n학원 컨셉에 맞게 \n찍어주시려고 애쓰시는 모습이 \n역시 소문대로였습니다^^\n작가님의 유머있는 웃음 유도로 \n선생님들이랑 재미있는 추억만들고.\n학원 홍보용으로 잘 활용하고있어요\n메이컵.헤어도  정성껏  고쳐주신\n예쁜 원장님도 감사드리구요♡","media":[{"src":"images/reviews/6ab9ea0a122c555ed4c4b43f-1.jpg"},{"src":"images/reviews/6ab9ea0a122c555ed4c4b43f-2.jpg"}]},
  {"id":"6aa0897915e082df53f49dc6","name":"ㅇ**","type":"리마인드웨딩","date":"2026.09","text":"시설도 깔끔하고 직원분들도 너무친절하시네요\n가족사진 이나 웨딩사진 좋아요\n덕분에 좋은 사진 간직하게되었네요\n다음에 또 이용할께요\n주변에도 꼭 추천합니다👍👍👍","media":[{"src":"images/reviews/6aa0897915e082df53f49dc6-1.jpg"},{"src":"images/reviews/6aa0897915e082df53f49dc6-2.jpg"}]},
  {"id":"6a9fef05e86fed367c711586","name":"알**","type":"리마인드웨딩","date":"2026.09","text":"스튜디오 휴무일에 급하게 부탁하여 가족 사진을 찍게 되었는데 너무친절하게 응대해 주시고 부모님 리마인드 웨딩 사진까지 너무 감사합니다\n저희 가족의 너무 아름 다운 추억을 만들어 주신 사랑이야기 스튜디오 감사합니다","media":[{"src":"images/reviews/6a9fef05e86fed367c711586-1.jpg"}]},
  {"id":"6a895d47cfa3bfd82e446af5","name":"쭌**","type":"우정사진","date":"2026.08","text":"친구들이랑 우정사진 찍고 왔는데 사진 받아보고 너무 마음에 들어서 리뷰 남겨요!\n\n사실 사진 찍을 때 어색할까 봐 조금 걱정했는데 생각보다 편하게 찍을 수 있었어요. 중간중간 분위기도 잘 풀어주시고 자연스럽게 포즈 잡을 수 있게 도와주셔서 웃으면서 촬영했던 것 같아요ㅎㅎ\n\n사진도 너무 예쁘게 나와서 친구들이랑 사진 보면서 계속 감탄했어요😂 그냥 사진 한 번 찍고 끝나는 게 아니라 그날 친구들이랑 놀았던 기억까지 같이 남는 느낌이라 더 좋네요.\n\n우정사진 찍을 곳 찾고 계시면 추천하고 싶어요! 덕분에 좋은 추억 예쁘게 남겼습니다. 감사합니다☺️","media":[{"src":"images/reviews/6a895d47cfa3bfd82e446af5-1.jpg"},{"src":"images/reviews/6a895d47cfa3bfd82e446af5-2.jpg"},{"src":"images/reviews/6a895d47cfa3bfd82e446af5-3.jpg"}]},
  {"id":"6a89431b6006b7373a7a5070","name":"졍**","type":"리마인드웨딩","date":"2026.08","text":"부모님 리마인드웨딩 촬영하러 사랑이야기스튜디오 다녀왔어요💐\n\n처음에는 부모님도 조금 어색해하셨는데 촬영하면서 분위기를 편하게 만들어주셔서 생각보다 훨씬 즐겁게 촬영했어요ㅎㅎ\n포즈도 하나하나 자연스럽게 알려주시고, 표정이나 자세도 예쁘게 잡아주셔서 사진 찍는 내내 편했어요.\n\n무엇보다 부모님이 드레스랑 턱시도 입으신 모습을 다시 보니까 괜히 뭉클하더라구요🥹\n결혼하셨을 때와는 또 다른 느낌으로 두 분의 모습을 예쁘게 남길 수 있어서 정말 만족스러웠어요.\n\n가격도 부담스럽지 않았는데 작가님께서 촬영까지 친절하게 해주셔서 더 좋았어요! 잘 찍어주셔서 고르기 힘들었어요!! 수정본이 기대가 됩니다😁 \n\n덕분에 오래오래 간직할 예쁜 사진과 추억 남겼어요📸\n별점 5점 드립니다✨","media":[{"src":"images/reviews/6a89431b6006b7373a7a5070-1.jpg"}]},
  {"id":"6a816e8039994841a25d5300","name":"i**","type":"가족사진","date":"2026.08","text":"포즈도 잘 잡아주시고 형식적인 사진이 아니라 다양한 구도로 추천해주셔서 좋았습니다! 사진에 정말 진심을 담아서 섬세하게 찍어주시고 파우더룸도 잘돼있습니다 직원분들도 친절하게 잘챙겨주셔서 다음에 또 올 것 같네요","media":[{"src":"images/reviews/6a816e8039994841a25d5300-1.jpg"}]},
  {"id":"6a8171f781d12fa6cf4e04d4","name":"j**","type":"리마인드웨딩","date":"2026.08","text":"아빠 칠순이라 가족사진 알아보던중에 사랑이야기 사진 이쁘게 잘 찍어주신다는 얘기듣고 예약했어요~~ \n부산  경기도에서 사진찍으러 구미까지 왔는데 너무 이쁘게 잘 찍어주셔서 예약한 보람이 있더라구요 ㅎ\n부모님 메이크업도 서비스로 해주셨고요~~ \n부모님 리마인드웨딩 사진 찍었는데 너무 좋아하시고 마음에 들어하셔서 저희도 뿌듯했답니다♡\n드레스 종류도 다양하고 \n애기도 있고 3대가 찍는 사진인데\n사장님 사진찍는 스킬이 최고셔요~~\n다음엔 시댁식구들하고 또 찍으러 올께요~~\n오늘 너무 감사했어요~~\n액자도 이쁘게 부탁드려요♡","media":[{"src":"images/reviews/6a8171f781d12fa6cf4e04d4-1.jpg"},{"src":"images/reviews/6a8171f781d12fa6cf4e04d4-2.jpg"},{"src":"images/reviews/6a8171f781d12fa6cf4e04d4-3.jpg"}]},
];

/* ---------------------------------------------------------------------
   갤러리 사진 목록
   - 새 사진은 images 폴더에 넣고, 아래에 한 줄 추가하면 됩니다.
   - cat 은 family / remind / friends / id / passport / profile 중 하나
   --------------------------------------------------------------------- */
window.GALLERY = [
  { src: "images/family-big.jpg",              cat: "family",  alt: "3대 대가족이 흑백 의상으로 하트를 만든 가족사진" },
  { src: "images/family-denim.jpg",            cat: "family",  alt: "청청 데님 의상으로 맞춘 활기찬 가족사진" },
  { src: "images/family-chair.jpg",            cat: "family",  alt: "나무 의자에 앉은 흑백 코디 가족사진" },
  { src: "images/family-balloon.jpg",          cat: "family",  alt: "풍선을 들고 웃는 다섯 식구 가족사진" },
  { src: "images/family-hanbok.jpg",           cat: "family",  alt: "명절 한복을 입은 가족사진" },
  { src: "images/remind-couple.jpg",           cat: "remind",  alt: "턱시도와 웨딩드레스를 입은 부부 리마인드웨딩" },
  { src: "images/remind-mother-daughters.jpg", cat: "remind",  alt: "엄마와 두 딸이 함께 입은 웨딩드레스" },
  { src: "images/friends-ribbon.jpg",          cat: "friends", alt: "컬러 리본 머리띠를 한 친구들의 우정사진" },
  { src: "images/friends-lying.jpg",           cat: "friends", alt: "화이트 셔츠를 맞춰 입은 친구들의 우정사진" },
  // 증명·여권·프로필 사진이 준비되면 아래처럼 추가하세요.
  // { src: "images/id-1.jpg",       cat: "id",       alt: "증명사진" },
  // { src: "images/passport-1.jpg", cat: "passport", alt: "여권사진" },
  // { src: "images/profile-1.jpg",  cat: "profile",  alt: "프로필사진" },
  // [자동 갤러리 시작] 사진선택 폴더의 '사진_올리기'가 만드는 부분입니다. 직접 고치지 마세요.
  {"src":"images/gallery/family-large-001.jpg","cat":"family","sub":"대가족","alt":"대가족 촬영 사진"},
  {"src":"images/gallery/family-large-003.jpg","cat":"family","sub":"대가족","alt":"대가족 촬영 사진"},
  {"src":"images/gallery/family-large-005.jpg","cat":"family","sub":"대가족","alt":"대가족 촬영 사진"},
  {"src":"images/gallery/family-large-009.jpg","cat":"family","sub":"대가족","alt":"대가족 촬영 사진"},
  {"src":"images/gallery/family-large-010.jpg","cat":"family","sub":"대가족","alt":"대가족 촬영 사진"},
  {"src":"images/gallery/family-large-020.jpg","cat":"family","sub":"대가족","alt":"대가족 촬영 사진"},
  {"src":"images/gallery/family-large-021.jpg","cat":"family","sub":"대가족","alt":"대가족 촬영 사진"},
  {"src":"images/gallery/family-large-026.jpg","cat":"family","sub":"대가족","alt":"대가족 촬영 사진"},
  {"src":"images/gallery/family-large-027.jpg","cat":"family","sub":"대가족","alt":"대가족 촬영 사진"},
  {"src":"images/gallery/family-large-033.jpg","cat":"family","sub":"대가족","alt":"대가족 촬영 사진"},
  {"src":"images/gallery/family-large-035.jpg","cat":"family","sub":"대가족","alt":"대가족 촬영 사진"},
  {"src":"images/gallery/family-large-038.jpg","cat":"family","sub":"대가족","alt":"대가족 촬영 사진"},
  {"src":"images/gallery/family-large-046.jpg","cat":"family","sub":"대가족","alt":"대가족 촬영 사진"},
  {"src":"images/gallery/family-large-051.jpg","cat":"family","sub":"대가족","alt":"대가족 촬영 사진"},
  {"src":"images/gallery/family-large-062.jpg","cat":"family","sub":"대가족","alt":"대가족 촬영 사진"},
  {"src":"images/gallery/family-large-073.jpg","cat":"family","sub":"대가족","alt":"대가족 촬영 사진"},
  {"src":"images/gallery/family-large-077.jpg","cat":"family","sub":"대가족","alt":"대가족 촬영 사진"},
  {"src":"images/gallery/family-large-081.jpg","cat":"family","sub":"대가족","alt":"대가족 촬영 사진"},
  {"src":"images/gallery/family-large-004.jpg","cat":"family","sub":"대가족","alt":"대가족 촬영 사진"},
  {"src":"images/gallery/family-large-017.jpg","cat":"family","sub":"대가족","alt":"대가족 촬영 사진"},
  {"src":"images/gallery/family-large-025.jpg","cat":"family","sub":"대가족","alt":"대가족 촬영 사진"},
  {"src":"images/gallery/family-large-028.jpg","cat":"family","sub":"대가족","alt":"대가족 촬영 사진"},
  {"src":"images/gallery/family-large-029.jpg","cat":"family","sub":"대가족","alt":"대가족 촬영 사진"},
  {"src":"images/gallery/family-large-030.jpg","cat":"family","sub":"대가족","alt":"대가족 촬영 사진"},
  {"src":"images/gallery/family-large-031.jpg","cat":"family","sub":"대가족","alt":"대가족 촬영 사진"},
  {"src":"images/gallery/family-large-032.jpg","cat":"family","sub":"대가족","alt":"대가족 촬영 사진"},
  {"src":"images/gallery/family-large-034.jpg","cat":"family","sub":"대가족","alt":"대가족 촬영 사진"},
  {"src":"images/gallery/family-large-036.jpg","cat":"family","sub":"대가족","alt":"대가족 촬영 사진"},
  {"src":"images/gallery/family-large-037.jpg","cat":"family","sub":"대가족","alt":"대가족 촬영 사진"},
  {"src":"images/gallery/family-large-041.jpg","cat":"family","sub":"대가족","alt":"대가족 촬영 사진"},
  {"src":"images/gallery/family-large-042.jpg","cat":"family","sub":"대가족","alt":"대가족 촬영 사진"},
  {"src":"images/gallery/family-large-043.jpg","cat":"family","sub":"대가족","alt":"대가족 촬영 사진"},
  {"src":"images/gallery/family-large-047.jpg","cat":"family","sub":"대가족","alt":"대가족 촬영 사진"},
  {"src":"images/gallery/family-large-048.jpg","cat":"family","sub":"대가족","alt":"대가족 촬영 사진"},
  {"src":"images/gallery/family-large-049.jpg","cat":"family","sub":"대가족","alt":"대가족 촬영 사진"},
  {"src":"images/gallery/family-large-050.jpg","cat":"family","sub":"대가족","alt":"대가족 촬영 사진"},
  {"src":"images/gallery/family-large-052.jpg","cat":"family","sub":"대가족","alt":"대가족 촬영 사진"},
  {"src":"images/gallery/family-large-053.jpg","cat":"family","sub":"대가족","alt":"대가족 촬영 사진"},
  {"src":"images/gallery/family-large-054.jpg","cat":"family","sub":"대가족","alt":"대가족 촬영 사진"},
  {"src":"images/gallery/family-large-063.jpg","cat":"family","sub":"대가족","alt":"대가족 촬영 사진"},
  {"src":"images/gallery/family-large-065.jpg","cat":"family","sub":"대가족","alt":"대가족 촬영 사진"},
  {"src":"images/gallery/family-large-066.jpg","cat":"family","sub":"대가족","alt":"대가족 촬영 사진"},
  {"src":"images/gallery/family-large-067.jpg","cat":"family","sub":"대가족","alt":"대가족 촬영 사진"},
  {"src":"images/gallery/family-large-070.jpg","cat":"family","sub":"대가족","alt":"대가족 촬영 사진"},
  {"src":"images/gallery/family-large-072.jpg","cat":"family","sub":"대가족","alt":"대가족 촬영 사진"},
  {"src":"images/gallery/family-large-075.jpg","cat":"family","sub":"대가족","alt":"대가족 촬영 사진"},
  {"src":"images/gallery/family-large-076.jpg","cat":"family","sub":"대가족","alt":"대가족 촬영 사진"},
  {"src":"images/gallery/family-large-079.jpg","cat":"family","sub":"대가족","alt":"대가족 촬영 사진"},
  {"src":"images/gallery/family-large-080.jpg","cat":"family","sub":"대가족","alt":"대가족 촬영 사진"},
  {"src":"images/gallery/family-small-002.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-003.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-004.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-006.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-009.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-012.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-014.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-021.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-028.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-033.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-034.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-036.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-042.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-044.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-058.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-064.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-077.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-083.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-086.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-087.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-098.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-099.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-109.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-113.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-001.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-005.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-007.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-008.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-015.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-016.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-017.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-025.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-026.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-029.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-030.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-031.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-032.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-035.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-037.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-039.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-040.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-041.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-045.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-046.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-047.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-048.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-049.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-051.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-054.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-055.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-060.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-062.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-063.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-065.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-066.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-072.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-073.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-074.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-078.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-079.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-080.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-082.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-084.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-085.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-089.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-091.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-101.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-104.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-105.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-106.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-small-111.jpg","cat":"family","sub":"소가족","alt":"소가족 촬영 사진"},
  {"src":"images/gallery/family-pet-001.jpg","cat":"family","sub":"반려동물과 함께","alt":"반려동물과 함께 촬영 사진"},
  {"src":"images/gallery/family-pet-003.jpg","cat":"family","sub":"반려동물과 함께","alt":"반려동물과 함께 촬영 사진"},
  {"src":"images/gallery/family-pet-004.jpg","cat":"family","sub":"반려동물과 함께","alt":"반려동물과 함께 촬영 사진"},
  {"src":"images/gallery/family-pet-005.jpg","cat":"family","sub":"반려동물과 함께","alt":"반려동물과 함께 촬영 사진"},
  {"src":"images/gallery/family-pet-008.jpg","cat":"family","sub":"반려동물과 함께","alt":"반려동물과 함께 촬영 사진"},
  {"src":"images/gallery/family-pet-009.jpg","cat":"family","sub":"반려동물과 함께","alt":"반려동물과 함께 촬영 사진"},
  {"src":"images/gallery/family-pet-002.jpg","cat":"family","sub":"반려동물과 함께","alt":"반려동물과 함께 촬영 사진"},
  {"src":"images/gallery/family-pet-006.jpg","cat":"family","sub":"반려동물과 함께","alt":"반려동물과 함께 촬영 사진"},
  {"src":"images/gallery/family-pet-007.jpg","cat":"family","sub":"반려동물과 함께","alt":"반려동물과 함께 촬영 사진"},
  {"src":"images/gallery/family-70th-001.jpg","cat":"family","sub":"칠순·팔순 상차림","alt":"칠순·팔순 상차림 촬영 사진"},
  {"src":"images/gallery/family-70th-002.jpg","cat":"family","sub":"칠순·팔순 상차림","alt":"칠순·팔순 상차림 촬영 사진"},
  {"src":"images/gallery/remind-001.jpg","cat":"remind","sub":"리마인드웨딩","alt":"리마인드웨딩 촬영 사진"},
  {"src":"images/gallery/remind-002.jpg","cat":"remind","sub":"리마인드웨딩","alt":"리마인드웨딩 촬영 사진"},
  {"src":"images/gallery/remind-003.jpg","cat":"remind","sub":"리마인드웨딩","alt":"리마인드웨딩 촬영 사진"},
  {"src":"images/gallery/remind-006.jpg","cat":"remind","sub":"리마인드웨딩","alt":"리마인드웨딩 촬영 사진"},
  {"src":"images/gallery/remind-007.jpg","cat":"remind","sub":"리마인드웨딩","alt":"리마인드웨딩 촬영 사진"},
  {"src":"images/gallery/remind-009.jpg","cat":"remind","sub":"리마인드웨딩","alt":"리마인드웨딩 촬영 사진"},
  {"src":"images/gallery/remind-010.jpg","cat":"remind","sub":"리마인드웨딩","alt":"리마인드웨딩 촬영 사진"},
  {"src":"images/gallery/remind-011.jpg","cat":"remind","sub":"리마인드웨딩","alt":"리마인드웨딩 촬영 사진"},
  {"src":"images/gallery/remind-014.jpg","cat":"remind","sub":"리마인드웨딩","alt":"리마인드웨딩 촬영 사진"},
  {"src":"images/gallery/remind-015.jpg","cat":"remind","sub":"리마인드웨딩","alt":"리마인드웨딩 촬영 사진"},
  {"src":"images/gallery/remind-022.jpg","cat":"remind","sub":"리마인드웨딩","alt":"리마인드웨딩 촬영 사진"},
  {"src":"images/gallery/remind-028.jpg","cat":"remind","sub":"리마인드웨딩","alt":"리마인드웨딩 촬영 사진"},
  {"src":"images/gallery/remind-030.jpg","cat":"remind","sub":"리마인드웨딩","alt":"리마인드웨딩 촬영 사진"},
  {"src":"images/gallery/remind-037.jpg","cat":"remind","sub":"리마인드웨딩","alt":"리마인드웨딩 촬영 사진"},
  {"src":"images/gallery/remind-040.jpg","cat":"remind","sub":"리마인드웨딩","alt":"리마인드웨딩 촬영 사진"},
  {"src":"images/gallery/remind-046.jpg","cat":"remind","sub":"리마인드웨딩","alt":"리마인드웨딩 촬영 사진"},
  {"src":"images/gallery/remind-004.jpg","cat":"remind","sub":"리마인드웨딩","alt":"리마인드웨딩 촬영 사진"},
  {"src":"images/gallery/remind-005.jpg","cat":"remind","sub":"리마인드웨딩","alt":"리마인드웨딩 촬영 사진"},
  {"src":"images/gallery/remind-008.jpg","cat":"remind","sub":"리마인드웨딩","alt":"리마인드웨딩 촬영 사진"},
  {"src":"images/gallery/remind-012.jpg","cat":"remind","sub":"리마인드웨딩","alt":"리마인드웨딩 촬영 사진"},
  {"src":"images/gallery/remind-013.jpg","cat":"remind","sub":"리마인드웨딩","alt":"리마인드웨딩 촬영 사진"},
  {"src":"images/gallery/remind-016.jpg","cat":"remind","sub":"리마인드웨딩","alt":"리마인드웨딩 촬영 사진"},
  {"src":"images/gallery/remind-017.jpg","cat":"remind","sub":"리마인드웨딩","alt":"리마인드웨딩 촬영 사진"},
  {"src":"images/gallery/remind-018.jpg","cat":"remind","sub":"리마인드웨딩","alt":"리마인드웨딩 촬영 사진"},
  {"src":"images/gallery/remind-021.jpg","cat":"remind","sub":"리마인드웨딩","alt":"리마인드웨딩 촬영 사진"},
  {"src":"images/gallery/remind-023.jpg","cat":"remind","sub":"리마인드웨딩","alt":"리마인드웨딩 촬영 사진"},
  {"src":"images/gallery/remind-025.jpg","cat":"remind","sub":"리마인드웨딩","alt":"리마인드웨딩 촬영 사진"},
  {"src":"images/gallery/remind-027.jpg","cat":"remind","sub":"리마인드웨딩","alt":"리마인드웨딩 촬영 사진"},
  {"src":"images/gallery/remind-038.jpg","cat":"remind","sub":"리마인드웨딩","alt":"리마인드웨딩 촬영 사진"},
  {"src":"images/gallery/remind-042.jpg","cat":"remind","sub":"리마인드웨딩","alt":"리마인드웨딩 촬영 사진"},
  {"src":"images/gallery/remind-043.jpg","cat":"remind","sub":"리마인드웨딩","alt":"리마인드웨딩 촬영 사진"},
  {"src":"images/gallery/remind-048.jpg","cat":"remind","sub":"리마인드웨딩","alt":"리마인드웨딩 촬영 사진"},
  {"src":"images/gallery/remind-050.jpg","cat":"remind","sub":"리마인드웨딩","alt":"리마인드웨딩 촬영 사진"},
  {"src":"images/gallery/remind-family-001.jpg","cat":"remind","sub":"가족 웨딩","alt":"가족 웨딩 촬영 사진"},
  {"src":"images/gallery/remind-family-002.jpg","cat":"remind","sub":"가족 웨딩","alt":"가족 웨딩 촬영 사진"},
  {"src":"images/gallery/remind-family-003.jpg","cat":"remind","sub":"가족 웨딩","alt":"가족 웨딩 촬영 사진"},
  {"src":"images/gallery/remind-family-007.jpg","cat":"remind","sub":"가족 웨딩","alt":"가족 웨딩 촬영 사진"},
  {"src":"images/gallery/remind-family-009.jpg","cat":"remind","sub":"가족 웨딩","alt":"가족 웨딩 촬영 사진"},
  {"src":"images/gallery/remind-family-012.jpg","cat":"remind","sub":"가족 웨딩","alt":"가족 웨딩 촬영 사진"},
  {"src":"images/gallery/remind-family-014.jpg","cat":"remind","sub":"가족 웨딩","alt":"가족 웨딩 촬영 사진"},
  {"src":"images/gallery/remind-family-017.jpg","cat":"remind","sub":"가족 웨딩","alt":"가족 웨딩 촬영 사진"},
  {"src":"images/gallery/remind-family-004.jpg","cat":"remind","sub":"가족 웨딩","alt":"가족 웨딩 촬영 사진"},
  {"src":"images/gallery/remind-family-005.jpg","cat":"remind","sub":"가족 웨딩","alt":"가족 웨딩 촬영 사진"},
  {"src":"images/gallery/remind-family-006.jpg","cat":"remind","sub":"가족 웨딩","alt":"가족 웨딩 촬영 사진"},
  {"src":"images/gallery/remind-family-008.jpg","cat":"remind","sub":"가족 웨딩","alt":"가족 웨딩 촬영 사진"},
  {"src":"images/gallery/remind-family-011.jpg","cat":"remind","sub":"가족 웨딩","alt":"가족 웨딩 촬영 사진"},
  {"src":"images/gallery/remind-family-013.jpg","cat":"remind","sub":"가족 웨딩","alt":"가족 웨딩 촬영 사진"},
  {"src":"images/gallery/remind-family-015.jpg","cat":"remind","sub":"가족 웨딩","alt":"가족 웨딩 촬영 사진"},
  {"src":"images/gallery/remind-family-016.jpg","cat":"remind","sub":"가족 웨딩","alt":"가족 웨딩 촬영 사진"},
  {"src":"images/gallery/remind-family-018.jpg","cat":"remind","sub":"가족 웨딩","alt":"가족 웨딩 촬영 사진"},
  {"src":"images/gallery/remind-mom-002.jpg","cat":"remind","sub":"엄마와 딸","alt":"엄마와 딸 촬영 사진"},
  {"src":"images/gallery/remind-mom-003.jpg","cat":"remind","sub":"엄마와 딸","alt":"엄마와 딸 촬영 사진"},
  {"src":"images/gallery/remind-mom-006.jpg","cat":"remind","sub":"엄마와 딸","alt":"엄마와 딸 촬영 사진"},
  {"src":"images/gallery/remind-mom-007.jpg","cat":"remind","sub":"엄마와 딸","alt":"엄마와 딸 촬영 사진"},
  {"src":"images/gallery/remind-mom-009.jpg","cat":"remind","sub":"엄마와 딸","alt":"엄마와 딸 촬영 사진"},
  {"src":"images/gallery/remind-mom-014.jpg","cat":"remind","sub":"엄마와 딸","alt":"엄마와 딸 촬영 사진"},
  {"src":"images/gallery/remind-mom-001.jpg","cat":"remind","sub":"엄마와 딸","alt":"엄마와 딸 촬영 사진"},
  {"src":"images/gallery/remind-mom-004.jpg","cat":"remind","sub":"엄마와 딸","alt":"엄마와 딸 촬영 사진"},
  {"src":"images/gallery/remind-mom-008.jpg","cat":"remind","sub":"엄마와 딸","alt":"엄마와 딸 촬영 사진"},
  {"src":"images/gallery/remind-mom-013.jpg","cat":"remind","sub":"엄마와 딸","alt":"엄마와 딸 촬영 사진"},
  {"src":"images/gallery/wedding-002.jpg","cat":"remind","sub":"웨딩·싱글웨딩","alt":"웨딩·싱글웨딩 촬영 사진"},
  {"src":"images/gallery/wedding-003.jpg","cat":"remind","sub":"웨딩·싱글웨딩","alt":"웨딩·싱글웨딩 촬영 사진"},
  {"src":"images/gallery/wedding-006.jpg","cat":"remind","sub":"웨딩·싱글웨딩","alt":"웨딩·싱글웨딩 촬영 사진"},
  {"src":"images/gallery/wedding-001.jpg","cat":"remind","sub":"웨딩·싱글웨딩","alt":"웨딩·싱글웨딩 촬영 사진"},
  {"src":"images/gallery/wedding-single-001.jpg","cat":"remind","sub":"웨딩·싱글웨딩","alt":"웨딩·싱글웨딩 촬영 사진"},
  {"src":"images/gallery/wedding-single-002.jpg","cat":"remind","sub":"웨딩·싱글웨딩","alt":"웨딩·싱글웨딩 촬영 사진"},
  {"src":"images/gallery/wedding-single-003.jpg","cat":"remind","sub":"웨딩·싱글웨딩","alt":"웨딩·싱글웨딩 촬영 사진"},
  {"src":"images/gallery/wedding-single-004.jpg","cat":"remind","sub":"웨딩·싱글웨딩","alt":"웨딩·싱글웨딩 촬영 사진"},
  {"src":"images/gallery/friends-001.jpg","cat":"friends","sub":"우정사진","alt":"우정사진 촬영 사진"},
  {"src":"images/gallery/friends-007.jpg","cat":"friends","sub":"우정사진","alt":"우정사진 촬영 사진"},
  {"src":"images/gallery/friends-013.jpg","cat":"friends","sub":"우정사진","alt":"우정사진 촬영 사진"},
  {"src":"images/gallery/friends-015.jpg","cat":"friends","sub":"우정사진","alt":"우정사진 촬영 사진"},
  {"src":"images/gallery/friends-020.jpg","cat":"friends","sub":"우정사진","alt":"우정사진 촬영 사진"},
  {"src":"images/gallery/friends-021.jpg","cat":"friends","sub":"우정사진","alt":"우정사진 촬영 사진"},
  {"src":"images/gallery/friends-027.jpg","cat":"friends","sub":"우정사진","alt":"우정사진 촬영 사진"},
  {"src":"images/gallery/friends-029.jpg","cat":"friends","sub":"우정사진","alt":"우정사진 촬영 사진"},
  {"src":"images/gallery/friends-031.jpg","cat":"friends","sub":"우정사진","alt":"우정사진 촬영 사진"},
  {"src":"images/gallery/friends-033.jpg","cat":"friends","sub":"우정사진","alt":"우정사진 촬영 사진"},
  {"src":"images/gallery/friends-036.jpg","cat":"friends","sub":"우정사진","alt":"우정사진 촬영 사진"},
  {"src":"images/gallery/friends-040.jpg","cat":"friends","sub":"우정사진","alt":"우정사진 촬영 사진"},
  {"src":"images/gallery/friends-046.jpg","cat":"friends","sub":"우정사진","alt":"우정사진 촬영 사진"},
  {"src":"images/gallery/friends-003.jpg","cat":"friends","sub":"우정사진","alt":"우정사진 촬영 사진"},
  {"src":"images/gallery/friends-006.jpg","cat":"friends","sub":"우정사진","alt":"우정사진 촬영 사진"},
  {"src":"images/gallery/friends-009.jpg","cat":"friends","sub":"우정사진","alt":"우정사진 촬영 사진"},
  {"src":"images/gallery/friends-010.jpg","cat":"friends","sub":"우정사진","alt":"우정사진 촬영 사진"},
  {"src":"images/gallery/friends-014.jpg","cat":"friends","sub":"우정사진","alt":"우정사진 촬영 사진"},
  {"src":"images/gallery/friends-016.jpg","cat":"friends","sub":"우정사진","alt":"우정사진 촬영 사진"},
  {"src":"images/gallery/friends-017.jpg","cat":"friends","sub":"우정사진","alt":"우정사진 촬영 사진"},
  {"src":"images/gallery/friends-018.jpg","cat":"friends","sub":"우정사진","alt":"우정사진 촬영 사진"},
  {"src":"images/gallery/friends-019.jpg","cat":"friends","sub":"우정사진","alt":"우정사진 촬영 사진"},
  {"src":"images/gallery/friends-022.jpg","cat":"friends","sub":"우정사진","alt":"우정사진 촬영 사진"},
  {"src":"images/gallery/friends-024.jpg","cat":"friends","sub":"우정사진","alt":"우정사진 촬영 사진"},
  {"src":"images/gallery/friends-025.jpg","cat":"friends","sub":"우정사진","alt":"우정사진 촬영 사진"},
  {"src":"images/gallery/friends-026.jpg","cat":"friends","sub":"우정사진","alt":"우정사진 촬영 사진"},
  {"src":"images/gallery/friends-028.jpg","cat":"friends","sub":"우정사진","alt":"우정사진 촬영 사진"},
  {"src":"images/gallery/friends-030.jpg","cat":"friends","sub":"우정사진","alt":"우정사진 촬영 사진"},
  {"src":"images/gallery/friends-032.jpg","cat":"friends","sub":"우정사진","alt":"우정사진 촬영 사진"},
  {"src":"images/gallery/friends-034.jpg","cat":"friends","sub":"우정사진","alt":"우정사진 촬영 사진"},
  {"src":"images/gallery/friends-035.jpg","cat":"friends","sub":"우정사진","alt":"우정사진 촬영 사진"},
  {"src":"images/gallery/friends-039.jpg","cat":"friends","sub":"우정사진","alt":"우정사진 촬영 사진"},
  {"src":"images/gallery/friends-042.jpg","cat":"friends","sub":"우정사진","alt":"우정사진 촬영 사진"},
  {"src":"images/gallery/friends-044.jpg","cat":"friends","sub":"우정사진","alt":"우정사진 촬영 사진"},
  {"src":"images/gallery/friends-045.jpg","cat":"friends","sub":"우정사진","alt":"우정사진 촬영 사진"},
  {"src":"images/gallery/friends-047.jpg","cat":"friends","sub":"우정사진","alt":"우정사진 촬영 사진"},
  {"src":"images/gallery/friends-050.jpg","cat":"friends","sub":"우정사진","alt":"우정사진 촬영 사진"},
  {"src":"images/gallery/friends-052.jpg","cat":"friends","sub":"우정사진","alt":"우정사진 촬영 사진"},
  {"src":"images/gallery/friends-054.jpg","cat":"friends","sub":"우정사진","alt":"우정사진 촬영 사진"},
  {"src":"images/gallery/profile-001.jpg","cat":"profile","sub":"프로필","alt":"프로필 촬영 사진"},
  {"src":"images/gallery/profile-002.jpg","cat":"profile","sub":"프로필","alt":"프로필 촬영 사진"},
  {"src":"images/gallery/profile-004.jpg","cat":"profile","sub":"프로필","alt":"프로필 촬영 사진"},
  {"src":"images/gallery/profile-005.jpg","cat":"profile","sub":"프로필","alt":"프로필 촬영 사진"},
  {"src":"images/gallery/profile-007.jpg","cat":"profile","sub":"프로필","alt":"프로필 촬영 사진"},
  {"src":"images/gallery/profile-011.jpg","cat":"profile","sub":"프로필","alt":"프로필 촬영 사진"},
  {"src":"images/gallery/profile-013.jpg","cat":"profile","sub":"프로필","alt":"프로필 촬영 사진"},
  {"src":"images/gallery/profile-016.jpg","cat":"profile","sub":"프로필","alt":"프로필 촬영 사진"},
  {"src":"images/gallery/profile-021.jpg","cat":"profile","sub":"프로필","alt":"프로필 촬영 사진"},
  {"src":"images/gallery/profile-023.jpg","cat":"profile","sub":"프로필","alt":"프로필 촬영 사진"},
  {"src":"images/gallery/profile-003.jpg","cat":"profile","sub":"프로필","alt":"프로필 촬영 사진"},
  {"src":"images/gallery/profile-006.jpg","cat":"profile","sub":"프로필","alt":"프로필 촬영 사진"},
  {"src":"images/gallery/profile-008.jpg","cat":"profile","sub":"프로필","alt":"프로필 촬영 사진"},
  {"src":"images/gallery/profile-009.jpg","cat":"profile","sub":"프로필","alt":"프로필 촬영 사진"},
  {"src":"images/gallery/profile-012.jpg","cat":"profile","sub":"프로필","alt":"프로필 촬영 사진"},
  {"src":"images/gallery/profile-015.jpg","cat":"profile","sub":"프로필","alt":"프로필 촬영 사진"},
  {"src":"images/gallery/profile-017.jpg","cat":"profile","sub":"프로필","alt":"프로필 촬영 사진"},
  {"src":"images/gallery/profile-019.jpg","cat":"profile","sub":"프로필","alt":"프로필 촬영 사진"},
  {"src":"images/gallery/profile-020.jpg","cat":"profile","sub":"프로필","alt":"프로필 촬영 사진"},
  {"src":"images/gallery/profile-022.jpg","cat":"profile","sub":"프로필","alt":"프로필 촬영 사진"},
  {"src":"images/gallery/profile-senior-001.jpg","cat":"profile","sub":"장수사진","alt":"장수사진 촬영 사진"},
  {"src":"images/gallery/profile-senior-003.jpg","cat":"profile","sub":"장수사진","alt":"장수사진 촬영 사진"},
  {"src":"images/gallery/profile-senior-004.jpg","cat":"profile","sub":"장수사진","alt":"장수사진 촬영 사진"},
  {"src":"images/gallery/profile-senior-005.jpg","cat":"profile","sub":"장수사진","alt":"장수사진 촬영 사진"},
  {"src":"images/gallery/profile-senior-006.jpg","cat":"profile","sub":"장수사진","alt":"장수사진 촬영 사진"},
  {"src":"images/gallery/profile-senior-007.jpg","cat":"profile","sub":"장수사진","alt":"장수사진 촬영 사진"},
  {"src":"images/gallery/profile-senior-009.jpg","cat":"profile","sub":"장수사진","alt":"장수사진 촬영 사진"},
  {"src":"images/gallery/profile-senior-011.jpg","cat":"profile","sub":"장수사진","alt":"장수사진 촬영 사진"},
  {"src":"images/gallery/profile-senior-013.jpg","cat":"profile","sub":"장수사진","alt":"장수사진 촬영 사진"},
  {"src":"images/gallery/profile-senior-015.jpg","cat":"profile","sub":"장수사진","alt":"장수사진 촬영 사진"},
  {"src":"images/gallery/profile-senior-002.jpg","cat":"profile","sub":"장수사진","alt":"장수사진 촬영 사진"},
  {"src":"images/gallery/profile-senior-008.jpg","cat":"profile","sub":"장수사진","alt":"장수사진 촬영 사진"},
  {"src":"images/gallery/profile-senior-010.jpg","cat":"profile","sub":"장수사진","alt":"장수사진 촬영 사진"},
  {"src":"images/gallery/profile-senior-012.jpg","cat":"profile","sub":"장수사진","alt":"장수사진 촬영 사진"},
  {"src":"images/gallery/profile-senior-014.jpg","cat":"profile","sub":"장수사진","alt":"장수사진 촬영 사진"},
  {"src":"images/gallery/profile-senior-016.jpg","cat":"profile","sub":"장수사진","alt":"장수사진 촬영 사진"},
  // [자동 갤러리 끝]
];
